apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.container.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Values.container.name }}-svc
          servicePort: 80
