apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-svc
  labels:
    app: {{ .Values.container.name }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.container.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.container.name }}
